### ISSUE TITLE
Sticky Keys

### ISSUE THREAD

**Issue by nikhiljha** [CE-Programming/CEmu#341]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS Catalina 10.15.1
**CEmu version:** v1.3 (87c3b43)
**Describe your issue:**  
Clicking on keys makes them stuck (as if they had been held down) until another key is pressed or a non-key portion of the keypad is clicked.

What are the steps to reproduce this issue?
-------------------------------------------
1. Click some keys.
2. They get stuck.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
<img width="552" alt="Screen Shot 2019-12-19 at 3 09 46 PM" src="https://user-images.githubusercontent.com/2773700/71217164-9da97a00-2271-11ea-8778-40a5a53d2972.png">

Keys stay red like this (I'm not clicking anything in the screenshot). I don't see a place to get logs, unless that means the console, in which case that looks normal.

```
[CEmu] Initialized Server [Calculator | cemu-20883]
[CEmu] Initialized Debugger...
[CEmu] Loading Emulator Image...
[CEmu] Initialized Memory...
[CEmu] Initialized CPU...
[CEmu] Initialized Control Ports...
[CEmu] Initialized Flash...
[CEmu] Initialized SHA256 Chip...
[CEmu] Initialized Universal Serial Bus...
[CEmu] Initialized LCD...
[CEmu] Initialized Interrupt Controller...
[CEmu] Initialized Watchdog Timer...
[CEmu] Initialized General Purpose Timers...
[CEmu] Initialized Real Time Clock...
[CEmu] Initialized Protected Ports...
[CEmu] Initialized Keypad...
[CEmu] Initialized Backlight...
[CEmu] Initialized Serial Peripheral Interface...
[CEmu] Initialized Advanced Peripheral Bus...
[CEmu] Initialized ASIC...
[CEmu] Memory reset.
[CEmu] LCD reset.
[CEmu] Keypad reset.
[CEmu] GPT reset.
[CEmu] RTC reset.
[CEmu] Watchdog timer reset.
[CEmu] CPU reset.
[CEmu] SHA256 chip reset.
[CEmu] USB Reset.
[CEmu] Control reset.
[CEmu] Loaded Emulator Image.
[CEmu] Freed Memory.
[CEmu] Freed ASIC.
[CEmu] Loading ROM Image...
[CEmu] Freed Memory.
[CEmu] Freed ASIC.
[CEmu] Initialized Memory...
[CEmu] Initialized CPU...
[CEmu] Initialized Control Ports...
[CEmu] Initialized Flash...
[CEmu] Initialized SHA256 Chip...
[CEmu] Initialized Universal Serial Bus...
[CEmu] Initialized LCD...
[CEmu] Initialized Interrupt Controller...
[CEmu] Initialized Watchdog Timer...
[CEmu] Initialized General Purpose Timers...
[CEmu] Initialized Real Time Clock...
[CEmu] Initialized Protected Ports...
[CEmu] Initialized Keypad...
[CEmu] Initialized Backlight...
[CEmu] Initialized Serial Peripheral Interface...
[CEmu] Initialized Advanced Peripheral Bus...
[CEmu] Initialized ASIC...
[CEmu] Loaded ROM Image.
[CEmu] Memory reset.
[CEmu] LCD reset.
[CEmu] Keypad reset.
[CEmu] GPT reset.
[CEmu] RTC reset.
[CEmu] Watchdog timer reset.
[CEmu] CPU reset.
[CEmu] SHA256 chip reset.
[CEmu] USB Reset.
[CEmu] Control reset.
```

**Comment by adriweb** [comment]
Hi,

Which mac computer is that on? (Which) Mouse or touchpad/trackpad? 
Is there any possibility a right-click was triggered when you click on the buttons? Because that's the expected behaviour for right clicking.

I can't reproduce the issue on my mac, obviously :(

**Comment by nikhiljha** [comment]
It's a 2016 MacBook Pro, but I'm certain I didn't accidentally right click. I've never accidentally right clicked something in any other application, but I can consistently reproduce this issue in CEmu.

That said, I just found out the issue *only* happens with a trackpad. A Bluetooth mouse that I tried doesn't have this issue. I wonder if there's something weird about clicking on a trackpad vs a mouse.

**Comment by AlexHarkness** [comment]
Same issue here. It only happens for me when Using Tap to click on the trackpad of my 2016 MacBook air running Catalina. A full click where I actually press down does not do this.

**Comment by denn333** [comment]
I'll add my voice to this concern — it makes the calculator completely unusable.

It also happens almost immediately. Key downs make the keys red and they stay that way. And random keys on the keypad suddenly turn red even when not pressed.

v. 1.3 and MacOS Catalina 10.15.7

**Comment by denn333** [comment]
I tried earlier builds, too. Is there a build where this is NOT an issue? I came here to recommend this tool to high school students.

**Comment by adriweb** [comment]
@denn333 can you give more information about your setup/settings? (see previous comments). I'm still unable to reproduce the issue here, and haven't since the beginning of CEmu in 2015 in fact.

**Comment by adriweb** [comment]
(Also, are all students using macs? Regardless, it would be nice to get more feedback about this and hopefully find a common point between all the computers with this bad behavior)

**Comment by denn333** [comment]
Thanks or the follow-up questions. The issues were trackpad-related, yes. It's a 2019 Macbook Pro. I tried on a 2014 machine also, and the problem did not appear actually.

Buttons randomly stay red and lock the screen and/or randomly press, too.
It's almost like trackpad down and up events are registering wrong.
Tapping in the space *around* the buttons usually clears the issue temporarily, but it comes back soon.

Also, I am using it with the default settings — no custom settings. So it actually does not look like the snapshot above (which I have not been able to accomplish, actually, without a window border dividing the display and the keypad panes) but rather a side-by-side pane format.

**Comment by danawcook** [comment]
Unsure if appropriate to reply, but I am encountering same issue with 2020 MBP 16 inch and did not have such on old 2014 box.  I reload the ROM and that seemed to work but yesterday during class it was exhibiting same behavior and actually shut down.  Feels like typical internet lag with button sitting on “red.”  Hope my addition helps.

**Comment by adriweb** [comment]
Thanks for the replies, any feedback is good to take, it may help track down what's going on.

I'm not sure what I can do _right now_ about the issue specifically, but maybe I can try to provide you with a latest build made with Qt 6.0 (that's beta) and see if they handled the input events differently/better.

**Comment by denn333** [comment]
@adriweb  I'm very, very happy to try for you. Honestly, I am not savvy enough to make my own builds, or I would have given it a shot. And I will also say that I appreciate that fact that you even responded, let alone so fast and proactively. Very generous of you.

**Comment by danawcook** [comment]
I am also willing to beta for you and write up observations but a programmer I am not.  And I would add to denn333’s comments:  my experience seeing your name goes back to WabbitEmu having used that product for years on my Mac was over-the-moon when I found CEmu.  Thank you for all your work.

Respectfully,

dana

**Comment by adriweb** [comment]
I haven't had the time to do the Qt 6.0 build, but let's try this one for now... It's recent enough, so maybe there will be changes already.
Thanks.

[CEmu_macOS.dmg.zip](https://github.com/CE-Programming/CEmu/files/5467159/CEmu_macOS.dmg.zip)

**Comment by denn333** [comment]
Sorry, this build has similar issues. Some things I caught on video for you: 

[https://youtu.be/d1GBKbC5QAc](url)
1) Some taps that register in the keypad history do not correspond to reactions by the calculator (either the pink-color keypress indicator or data entry). In the video, I gently tap and the number 8 registers in the keypress list, but not as a Mac system touch OR as a reaction by the calculator. 

[https://youtu.be/IZeptXlJVLc](url)
2) Somehow, a slight movement when pressing a key can trigger extra keypress events that then cause strange behaviors. In this video, the first four clicks (not just taps) on the touchpad of the 8 key behaved correctly. The fifth one triggered a whole bunch of keypresses of 8 *and* 2. This video then continues to show how clicking the 8 key triggered a whole bunch of 8 and [(] keypress events and corresponding action on the calculator even though all I was doing was dragging the cursor, not tapping or clicking.

No video...
3) When buttons get "stuck" this way, sometimes keys nowhere near the cursor get triggered. No video, but for example, when the 6 key got once got stuck, I dragged around, and the "math", "x⁻¹" and "x²" keys kept triggering without the cursor even being near them.

Unrelated, but making the delete key trigger the "mode" button by default causes people troubles.)

**Comment by adriweb** [comment]
Thanks for the detailed feedback!
(Videos are private however, could you change them to at least unlisted? :))

I really need to find a way to reproduce on my side before I can start tinkering with workarounds, though :(
I mean, I could add debug logs here and there and ask you to send that to me, but that would take so much time...

It really sucks that this seems to be a Qt issue. It would be nice to be able to create a minimap qt app to try to repro, and then submit that on the qt bug tracker.

**Comment by denn333** [comment]
@adriweb I fixed the videos. Sorry about that. My mistake.

**Comment by danawcook** [comment]
Adrien,

For some time, I did not get back to using CEmu as the curriculum did not involve calculator work in the later month.  But, knowing that it is coming up, I checked for an update and reset the device, etc and, of course, I am encountering this issue still/again.  

I cannot locate the beta link that you forwarded and cannot locate the email it was contained in.  

Is it possible to have that again unless you know that the problem persists with that build then I will search for an alternative solution to my problem.

Thank you for your time.

With great respect,


Respectfully,

DANA W COOK
Teacher, Mathematics
老师，数学
@danawcook
www.danawcook.com
youtube.com/danawcook

“Intelligence plus character is the true goal of education.”

						- Dr. Martin Luther King, Jr.

**Comment by sdnjack** [comment]
I'm not sure if I'm seeing the same thing or not. I've been using CEmu on a HP touchscreen laptop. If I use my finger to push the buttons on the calculator, it works just fine. If I use my HP pen and tap the buttons, they go red and stick. I have to use the mouse to unstick them. I learned today that if I make a little swipe with the pen, like I'm writing a dash on the key, it does not stick and works fine. I also learned that if I drag the pen from key to key, each key I hit shows up on the screen. Not sure if that's  a feature or a bug, but I thought it was worth noting and might help you get to the bottom of things.

**Comment by adriweb** [comment]
ACK, thanks for the updates, but I'm still not able to repro this on my hardware. I'll check about the latest beta, since this will be more up to date. I'll update this ticket with a new link.

---

Previous reply by @danawcook :
```
Mac OS Catalina (and now still on Big Sur having upgraded this past weekend) on MacBook Pro 16 inch, intel processor

CEmu v1.3 (git: 87c3b43)

When using CEmu with the built-in apple trackpad, buttons seem to stick and/or the Rom becomes frozen.  The solution for me was to bring a mouse to my office so that I can conduct my remote classes as this does not occur when not using the trackpad.  This is true at home with a USB-A mouse via aUSB-A keyboard via a USB-A hub, as well as a USB-A mouse via a USB-A hub.  To bring the mouse to office, I upgraded to Bluetooth trackball at home and using this as input device through built in Apple bluetooth, no issue.

This is not a new situation and was at some point offered the beta but I did not act quickly to secure the download.

Steps
1.  Open CEmu.
2. Use trackpad on MacBook Pro 16 inch, intel.  Unsure if it is an issue with other Macs.

The key shows red when this occurs, seemingly as if the process of pushing the button is frozen part way through the process of executing the button command.
```

**Comment by adriweb** [comment]
Alright, sorry for the delay, here's a signed+notarized macOS build of the current master branch, packaged with libs that should work from version 10.14 on.
[CEmu_beta_mac.zip](https://github.com/CE-Programming/CEmu/files/6239645/CEmu_beta_mac.zip)

Let me know how that goes...

(Considering it's v2.0/master, it has USB support, so you can even transfer apps and OSes)

**Comment by danawcook** [comment]
Thank you.  Will do.

**Comment by adriweb** [comment]
No feedback for a while, closing. Please reopen if needed (latest build available, FYI: https://github.com/CE-Programming/CEmu/suites/9505741049/artifacts/451063746)

**Comment by TheMiningTeamYT** [comment]
I've been experiencing a very similar issue on my Linux Laptop, though it doesn't seem to be exactly the same.
For example, unlike what @denn333 mentioned, clicking the area around the button seems to do nothing. The only thing that fixes the problem is reloading the ROM.
Attached are some videos of the bug.

https://github.com/CE-Programming/CEmu/assets/31364192/7d5da734-4611-4328-b42b-2f7ea88f7000

https://github.com/CE-Programming/CEmu/assets/31364192/2d5fba39-6177-40ab-bbd4-f50c4ba407d8
